/* This file was generated by the Hex-Rays decompiler version 9.0.0.240807.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void init_proc();
int sub_AE4();
// int __fastcall strcpy(_DWORD, _DWORD); weak
// int __fastcall popen(_DWORD, _DWORD); weak
// int __fastcall mosquitto_log_printf(_DWORD, _DWORD); weak
// int __fastcall pclose(int a1);
// int snprintf(_DWORD, _DWORD, const char *, ...); weak
// int __fastcall EVP_DigestFinal_ex(_DWORD, _DWORD, _DWORD); weak
// int __fastcall BIO_free_all(_DWORD); weak
// int __fastcall BIO_set_flags(_DWORD, _DWORD); weak
// int __fastcall memcpy(_DWORD, _DWORD, _DWORD); weak
// int _cxa_finalize(void *);
// int __fastcall feof(_DWORD); weak
// int __fastcall malloc(_DWORD); weak
// int __fastcall EVP_MD_CTX_free(_DWORD); weak
// int __fastcall BIO_ctrl(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall BIO_write(_DWORD, _DWORD, _DWORD); weak
// int __fastcall _deregister_frame_info(_DWORD); weak
// int __fastcall BIO_f_base64(_DWORD); weak
// int __fastcall BIO_new(_DWORD); weak
// int __fastcall strncmp(_DWORD, _DWORD, _DWORD); weak
// int __fastcall EVP_DigestInit_ex(_DWORD, _DWORD, _DWORD); weak
// int __fastcall strncpy(int a1, int a2, int a3);
// int __fastcall realloc(_DWORD, _DWORD); weak
// int __fastcall EVP_DigestUpdate(_DWORD, _DWORD, _DWORD); weak
// int __fastcall strncat(_DWORD, _DWORD, _DWORD); weak
// int __fastcall fread(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall RAND_bytes(_DWORD, _DWORD); weak
// int __fastcall strdup(_DWORD); weak
// int __fastcall memset(_DWORD, _DWORD, _DWORD); weak
// int __fastcall mosquitto_callback_unregister(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall BIO_push(_DWORD, _DWORD); weak
// int __fastcall BIO_s_mem(_DWORD); weak
// int _errno_location(void); weak
// int EVP_MD_CTX_new(void); weak
// int __fastcall strlen(_DWORD); weak
// int __fastcall mosquitto_callback_register(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _register_frame_info(_DWORD, _DWORD); weak
// int __fastcall free(_DWORD); weak
// int __fastcall EVP_get_digestbyname(_DWORD); weak
int start();
int sub_D60();
int __fastcall sub_D9C(int a1, int *a2);
int __fastcall miwifi_gen_random(_DWORD *a1, int a2);
int __fastcall miwifi_gen_sha(int a1, int *a2);
_BYTE *__fastcall miwifi_get_ifz_field(const char *a1, const char *a2);
_BYTE *__fastcall miwifi_get_wl_mac(const char *a1);
int __fastcall auth_check(int a1, int a2);
int __fastcall sub_16C8(int a1, int a2);
int __fastcall mosquitto_plugin_version(int a1, int a2);
int __fastcall mosquitto_plugin_init(int a1);
int mosquitto_plugin_cleanup();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int dword_1A14 = 0; // weak
int (*off_11F4C)(void) = &dword_0; // weak
_UNKNOWN *off_11FF0 = &_stack_chk_guard; // weak
_UNKNOWN *off_11FF4 = &__cxa_finalize; // weak
_UNKNOWN *off_11FF8 = &__deregister_frame_info; // weak
_UNKNOWN *off_11FFC = &__register_frame_info; // weak
_UNKNOWN *off_12000 = (_UNKNOWN *)0xFF012000; // weak
char byte_12004; // weak
_UNKNOWN unk_12008; // weak
int dword_12020; // weak


//----- (00000AD8) --------------------------------------------------------
void init_proc()
{
  ;
}

//----- (00000AE4) --------------------------------------------------------
int sub_AE4()
{
  return off_11F4C();
}
// 11F4C: using guessed type int (*off_11F4C)(void);

//----- (00000CD8) --------------------------------------------------------
int start()
{
  int result; // r0

  if ( !byte_12004 )
  {
    if ( off_11FF4 )
      result = _cxa_finalize(off_12000);
    if ( off_11FF8 )
      result = _deregister_frame_info(&dword_1A14);
    byte_12004 = 1;
  }
  return result;
}
// BC4: using guessed type int __fastcall _deregister_frame_info(_DWORD);
// 1A14: using guessed type int dword_1A14;
// 11FF4: using guessed type _UNKNOWN *off_11FF4;
// 11FF8: using guessed type _UNKNOWN *off_11FF8;
// 12000: using guessed type _UNKNOWN *off_12000;
// 12004: using guessed type char byte_12004;

//----- (00000D60) --------------------------------------------------------
int sub_D60()
{
  int result; // r0

  if ( off_11FFC )
    return _register_frame_info(&dword_1A14, &unk_12008);
  return result;
}
// CB4: using guessed type int __fastcall _register_frame_info(_DWORD, _DWORD);
// 1A14: using guessed type int dword_1A14;
// 11FFC: using guessed type _UNKNOWN *off_11FFC;

//----- (00000D9C) --------------------------------------------------------
int __fastcall sub_D9C(int a1, int *a2)
{
  int v2; // r3
  int v4; // r6
  int v5; // r0
  int v6; // r4
  unsigned int v7; // r7
  int v9; // r5
  _DWORD v10[73]; // [sp+4h] [bp-124h] BYREF

  v2 = *(_DWORD *)off_11FF0;
  memset(v10, 0, 256);
  v10[64] = v2;
  v4 = popen(a1, "r");
  if ( !v4 )
    return -1;
  v5 = malloc(256);
  v6 = v5;
  if ( !v5 )
  {
LABEL_12:
    pclose(v4);
    return -1;
  }
  v7 = 256;
  memset(v5, 0, 256);
  while ( !feof(v4) )
  {
    memset(v10, 0, 256);
    if ( fread(v10, 1, 256, v4) )
    {
      v9 = strlen(v6);
      if ( v9 + strlen(v10) + 1 >= v7 )
      {
        v7 *= 2;
        v6 = realloc(v6, v7);
        if ( !v6 )
          goto LABEL_12;
      }
      strncat(v6, v10, 256);
    }
    else if ( *(_DWORD *)_errno_location() != 4 )
    {
      break;
    }
  }
  pclose(v4);
  *a2 = v6;
  return 0;
}
// B04: using guessed type int __fastcall popen(_DWORD, _DWORD);
// B70: using guessed type int __fastcall feof(_DWORD);
// B7C: using guessed type int __fastcall malloc(_DWORD);
// C0C: using guessed type int __fastcall realloc(_DWORD, _DWORD);
// C24: using guessed type int __fastcall strncat(_DWORD, _DWORD, _DWORD);
// C30: using guessed type int __fastcall fread(_DWORD, _DWORD, _DWORD, _DWORD);
// C54: using guessed type int __fastcall memset(_DWORD, _DWORD, _DWORD);
// C84: using guessed type int _errno_location(void);
// C9C: using guessed type int __fastcall strlen(_DWORD);
// 11FF0: using guessed type _UNKNOWN *off_11FF0;

//----- (00000EF8) --------------------------------------------------------
int __fastcall miwifi_gen_random(_DWORD *a1, int a2)
{
  _DWORD *v4; // r2
  const char *v5; // r3
  int v6; // r0
  int v7; // r1
  _DWORD *v8; // r12
  int v9; // r0
  bool v10; // cc
  __int16 v11; // r1
  char v12; // r3
  int v13; // r0
  _BYTE *v14; // r5
  _BYTE *v15; // r6
  _BYTE v17[64]; // [sp+4h] [bp-64h] BYREF
  int v18; // [sp+44h] [bp-24h]

  v4 = v17;
  v18 = *(_DWORD *)off_11FF0;
  v5 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  do
  {
    v6 = *(_DWORD *)v5;
    v5 += 8;
    v7 = *((_DWORD *)v5 - 1);
    *v4 = v6;
    v4[1] = v7;
    v8 = v4 + 2;
    v4 += 2;
  }
  while ( v5 != "456789" );
  v9 = *(_DWORD *)v5;
  v10 = a2 <= 0;
  v11 = *((_WORD *)v5 + 2);
  if ( a2 <= 0 )
    a2 = 0;
  v12 = v5[6];
  *v8 = v9;
  *((_WORD *)v8 + 2) = v11;
  *((_BYTE *)v8 + 6) = v12;
  if ( !v10 )
  {
    v13 = malloc(a2 + 1);
    v14 = (_BYTE *)v13;
    if ( v13 )
    {
      if ( RAND_bytes(v13, a2) == 1 )
      {
        v15 = v14;
        do
        {
          *v15 = v17[*v15 % 0x3Eu];
          ++v15;
        }
        while ( &v14[a2] != v15 );
        *a1 = v14;
        v14[a2] = 0;
        return a2;
      }
      free(v14);
    }
    return -1;
  }
  return a2;
}
// B7C: using guessed type int __fastcall malloc(_DWORD);
// C3C: using guessed type int __fastcall RAND_bytes(_DWORD, _DWORD);
// CC0: using guessed type int __fastcall free(_DWORD);
// 11FF0: using guessed type _UNKNOWN *off_11FF0;

//----- (00001008) --------------------------------------------------------
int __fastcall miwifi_gen_sha(int a1, int *a2)
{
  int v4; // r3
  int digestbyname; // r10
  int v7; // r5
  int v8; // r0
  int v9; // r0
  int v10; // r10
  int v11; // r0
  int v12; // r5
  int v13; // r0
  int v14; // r0
  int v15; // r9
  int v16; // r5
  int v17; // r0
  int v18; // r10
  int v19; // r9
  int v20; // r0
  int v21; // r6
  int v22; // [sp+4h] [bp-84h] BYREF
  int v23; // [sp+8h] [bp-80h] BYREF
  char v24[8]; // [sp+Ch] [bp-7Ch] BYREF
  __int64 v25; // [sp+14h] [bp-74h]
  _DWORD v26[27]; // [sp+1Ch] [bp-6Ch] BYREF

  v4 = *(_DWORD *)off_11FF0;
  v22 = 0;
  v26[16] = v4;
  v24[7] = 0;
  *(_DWORD *)((char *)&v25 + 3) = 0;
  strcpy(v24, "miwifi");
  HIBYTE(v25) = 0;
  memset(v26, 0, 64);
  LODWORD(v25) = 1847789604;
  digestbyname = EVP_get_digestbyname("sha512");
  if ( !digestbyname )
    return -1;
  HIDWORD(v25) = 1143909;
  v7 = EVP_MD_CTX_new();
  EVP_DigestInit_ex(v7, digestbyname, 0);
  v8 = strlen(a1);
  EVP_DigestUpdate(v7, a1, v8);
  EVP_DigestUpdate(v7, v24, 16);
  EVP_DigestFinal_ex(v7, v26, &v22);
  v9 = EVP_MD_CTX_free(v7);
  v10 = v22;
  v23 = 0;
  v11 = BIO_f_base64(v9);
  v12 = BIO_new(v11);
  v13 = BIO_set_flags(v12, 256);
  v14 = BIO_s_mem(v13);
  v15 = BIO_new(v14);
  v16 = BIO_push(v12, v15);
  BIO_write(v16, v26, v10);
  if ( BIO_ctrl(v16, 11, 0, 0) == 1
    && (v17 = BIO_ctrl(v15, 3, 0, &v23), v18 = v17 + 1, v19 = v17, v20 = malloc(v17 + 1), (v21 = v20) != 0) )
  {
    memcpy(v20, v23, v18);
    *(_BYTE *)(v21 + v19) = 0;
    BIO_free_all(v16);
    *a2 = v21;
    return 0;
  }
  else
  {
    BIO_free_all(v16);
    return 1;
  }
}
// B34: using guessed type int __fastcall EVP_DigestFinal_ex(_DWORD, _DWORD, _DWORD);
// B40: using guessed type int __fastcall BIO_free_all(_DWORD);
// B4C: using guessed type int __fastcall BIO_set_flags(_DWORD, _DWORD);
// B58: using guessed type int __fastcall memcpy(_DWORD, _DWORD, _DWORD);
// B7C: using guessed type int __fastcall malloc(_DWORD);
// BA0: using guessed type int __fastcall EVP_MD_CTX_free(_DWORD);
// BAC: using guessed type int __fastcall BIO_ctrl(_DWORD, _DWORD, _DWORD, _DWORD);
// BB8: using guessed type int __fastcall BIO_write(_DWORD, _DWORD, _DWORD);
// BD0: using guessed type int __fastcall BIO_f_base64(_DWORD);
// BDC: using guessed type int __fastcall BIO_new(_DWORD);
// BF4: using guessed type int __fastcall EVP_DigestInit_ex(_DWORD, _DWORD, _DWORD);
// C18: using guessed type int __fastcall EVP_DigestUpdate(_DWORD, _DWORD, _DWORD);
// C54: using guessed type int __fastcall memset(_DWORD, _DWORD, _DWORD);
// C6C: using guessed type int __fastcall BIO_push(_DWORD, _DWORD);
// C78: using guessed type int __fastcall BIO_s_mem(_DWORD);
// C90: using guessed type int EVP_MD_CTX_new(void);
// C9C: using guessed type int __fastcall strlen(_DWORD);
// CCC: using guessed type int __fastcall EVP_get_digestbyname(_DWORD);
// 11FF0: using guessed type _UNKNOWN *off_11FF0;

//----- (000011EC) --------------------------------------------------------
_BYTE *__fastcall miwifi_get_ifz_field(const char *a1, const char *a2)
{
  bool v4; // zf
  _BYTE *result; // r0
  _BYTE *v6; // [sp+8h] [bp-120h] BYREF
  _BYTE v7[256]; // [sp+Ch] [bp-11Ch] BYREF
  int v8; // [sp+10Ch] [bp-1Ch]

  v8 = *(_DWORD *)off_11FF0;
  memset(v7, 0, sizeof(v7));
  v6 = 0;
  v4 = a2 == 0;
  if ( a2 )
    v4 = a1 == 0;
  if ( v4 )
    return 0;
  snprintf(
    v7,
    256,
    "bhifname=`uci -q get misc.backhauls.%s`;uci_sec=`uci show wireless |grep \"'$bhifname'\" |awk -F '.' '{print $1\".\""
    "$2}'`;uci -q get \"$uci_sec\".%s|tr -d ': \t\n"
    "\r' ",
    a1,
    a2);
  if ( sub_D9C((int)v7, (int *)&v6) )
    goto LABEL_10;
  result = v6;
  if ( !v6 )
    return 0;
  if ( !*v6 )
  {
LABEL_10:
    if ( v6 )
      free(v6);
    return 0;
  }
  return result;
}
// B28: using guessed type int snprintf(_DWORD, _DWORD, const char *, ...);
// C54: using guessed type int __fastcall memset(_DWORD, _DWORD, _DWORD);
// CC0: using guessed type int __fastcall free(_DWORD);
// 11FF0: using guessed type _UNKNOWN *off_11FF0;

//----- (000012C4) --------------------------------------------------------
_BYTE *__fastcall miwifi_get_wl_mac(const char *a1)
{
  _BYTE *result; // r0
  _BYTE *v3; // [sp+0h] [bp-118h] BYREF
  _BYTE v4[256]; // [sp+4h] [bp-114h] BYREF
  int v5; // [sp+104h] [bp-14h]

  v5 = *(_DWORD *)off_11FF0;
  memset(v4, 0, sizeof(v4));
  v3 = 0;
  if ( !a1 )
    return 0;
  snprintf(
    v4,
    256,
    "bhifname=`uci -q get misc.backhauls.%s` && ifconfig $bhifname |grep -o \"HWaddr [0-9A-F:]*\"|awk '{print $2}'|tr -d ': \r\n\t'",
    a1);
  if ( sub_D9C((int)v4, (int *)&v3) )
    goto LABEL_7;
  result = v3;
  if ( !v3 )
    return 0;
  if ( !*v3 )
  {
LABEL_7:
    if ( v3 )
      free(v3);
    return 0;
  }
  return result;
}
// B28: using guessed type int snprintf(_DWORD, _DWORD, const char *, ...);
// C54: using guessed type int __fastcall memset(_DWORD, _DWORD, _DWORD);
// CC0: using guessed type int __fastcall free(_DWORD);
// 11FF0: using guessed type _UNKNOWN *off_11FF0;

//----- (00001390) --------------------------------------------------------
int __fastcall auth_check(int a1, int a2)
{
  BOOL v4; // r1
  int v5; // r0
  _BYTE *v6; // r4
  int v7; // r5
  unsigned int v8; // r2
  const char *v9; // r0
  _BYTE *ifz_field; // r4
  int v11; // r4
  int v12; // r6
  _BYTE *v13; // r3
  _BYTE *v14; // r2
  _BYTE *v15; // r1
  int v16; // r0
  BOOL v17; // r3
  int v18; // r0
  _BYTE *v20; // [sp+10h] [bp-24h] BYREF
  _BYTE v21[32]; // [sp+14h] [bp-20h] BYREF
  char v22[256]; // [sp+34h] [bp+0h] BYREF
  _BYTE v23[256]; // [sp+134h] [bp+100h] BYREF
  int v24; // [sp+234h] [bp+200h]

  v24 = *(_DWORD *)off_11FF0;
  memset(v22, 0, sizeof(v22));
  v4 = a2 == 0;
  if ( !a1 )
    v4 = 1;
  if ( v4 )
    return -1;
  v20 = 0;
  memset(v23, 0, 64);
  strcpy(v23, "mesh_cmd backhaul get real_band");
  v5 = sub_D9C((int)v23, (int *)&v20);
  v6 = v20;
  if ( v5 )
    goto LABEL_7;
  if ( !v20 )
    return -1;
  if ( !*v20 )
  {
LABEL_7:
    if ( !v20 )
      return -1;
LABEL_10:
    free(v20);
    return -1;
  }
  v8 = strlen(v20);
  if ( v8 > 0x1F )
    goto LABEL_10;
  strncpy((int)v21, (int)v20, v8);
  v21[strlen(v6)] = 0;
  free(v6);
  if ( !strncmp(v21, "5gh", 4) )
    v9 = "backhaul_5gh_ap_iface";
  else
    v9 = "backhaul_5g_ap_iface";
  ifz_field = miwifi_get_ifz_field(v9, "key");
  if ( !ifz_field )
  {
    ifz_field = miwifi_get_ifz_field("backhaul_2g_ap_iface", "key");
    if ( !ifz_field )
      return -1;
  }
  strncpy((int)v22, (int)ifz_field, 256);
  free(ifz_field);
  v11 = strdup(a1);
  v12 = strdup(a2);
  memset(v23, 0, sizeof(v23));
  v13 = 0;
  v14 = (_BYTE *)v11;
  v20 = 0;
  v15 = 0;
  while ( *v14 )
  {
    if ( *v14 == 95 )
    {
      v16 = (unsigned __int8)v14[1];
      *v14 = 0;
      if ( !v16 )
        break;
      ++v14;
      if ( v15 )
      {
        if ( v13 )
          break;
        v13 = v14;
      }
      else
      {
        v15 = v14;
      }
    }
    ++v14;
  }
  v17 = v13 == 0;
  if ( !v15 )
    v17 = 1;
  if ( !v11 )
    v17 = 1;
  if ( !v17 && strlen(v11) == 16 && *(_BYTE *)v11 == 88 && *(_BYTE *)(v11 + 1) == 81 )
  {
    if ( snprintf(v23, 256, "%s_%s", (const char *)(v11 + 2), v22) < 0 || miwifi_gen_sha((int)v23, (int *)&v20) )
    {
      v7 = -1;
    }
    else
    {
      v18 = strlen(v20);
      v7 = -(strncmp(v12, v20, v18) != 0);
    }
    if ( v20 )
      free(v20);
    goto LABEL_39;
  }
  v7 = -1;
  if ( v11 )
LABEL_39:
    free(v11);
  if ( v12 )
    free(v12);
  return v7;
}
// AF8: using guessed type int __fastcall strcpy(_DWORD, _DWORD);
// B28: using guessed type int snprintf(_DWORD, _DWORD, const char *, ...);
// BE8: using guessed type int __fastcall strncmp(_DWORD, _DWORD, _DWORD);
// C48: using guessed type int __fastcall strdup(_DWORD);
// C54: using guessed type int __fastcall memset(_DWORD, _DWORD, _DWORD);
// C9C: using guessed type int __fastcall strlen(_DWORD);
// CC0: using guessed type int __fastcall free(_DWORD);
// 11FF0: using guessed type _UNKNOWN *off_11FF0;

//----- (000016C8) --------------------------------------------------------
int __fastcall sub_16C8(int a1, int a2)
{
  int result; // r0

  result = auth_check(*(_DWORD *)(a2 + 8), *(_DWORD *)(a2 + 12));
  if ( result )
  {
    mosquitto_log_printf(1, "Client auth failed!");
    return 11;
  }
  return result;
}
// B10: using guessed type int __fastcall mosquitto_log_printf(_DWORD, _DWORD);

//----- (00001700) --------------------------------------------------------
int __fastcall mosquitto_plugin_version(int a1, int a2)
{
  int i; // r2

  for ( i = 0; ; ++i )
  {
    if ( i >= a1 )
      return -1;
    if ( *(_DWORD *)(a2 + 4 * i) == 5 )
      break;
  }
  return 5;
}

//----- (0000172C) --------------------------------------------------------
int __fastcall mosquitto_plugin_init(int a1)
{
  mosquitto_log_printf(1, "Starting `mqtt-auth-plugin` for miwifi");
  dword_12020 = a1;
  mosquitto_callback_register(a1, 3, sub_16C8, 0, 0);
  return 0;
}
// B10: using guessed type int __fastcall mosquitto_log_printf(_DWORD, _DWORD);
// CA8: using guessed type int __fastcall mosquitto_callback_register(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 12020: using guessed type int dword_12020;

//----- (00001788) --------------------------------------------------------
int mosquitto_plugin_cleanup()
{
  mosquitto_log_printf(1, "Stopping `mqtt-auth-plugin`");
  mosquitto_callback_unregister(dword_12020, 3, sub_16C8, 0);
  return 0;
}
// B10: using guessed type int __fastcall mosquitto_log_printf(_DWORD, _DWORD);
// C60: using guessed type int __fastcall mosquitto_callback_unregister(_DWORD, _DWORD, _DWORD, _DWORD);
// 12020: using guessed type int dword_12020;

//----- (000017D0) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=95 queued=15 decompiled=15 lumina nreq=0 worse=0 better=0
// ALL OK, 15 function(s) have been successfully decompiled
