#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=cab_meshd
PROG="/usr/sbin/cab_meshd"

start_service() {
    [ -f "/usr/sbin/mqautogen.lua" ] && lua /usr/sbin/mqautogen.lua
    mesh_mode=$(uci -q get xiaoqiang.common.NETMODE)
    if [ "$mesh_mode" = "whc_re" -o "$mesh_mode" = "wifiapmode" -o "$mesh_mode" = "cpe_bridgemode" ]; then
        exit 0
    fi

    INITTED=$(uci -q get xiaoqiang.common.INITTED)
    local meshSupportRE=$(uci -q get misc.features.meshSupportRE)
    if [ -z "$meshSupportRE" ]; then
        meshSupportRE=1
    fi

    if [ "$INITTED" != "YES" ] && [ "$meshSupportRE" == "1" ]; then
        #RE
        wanif=$(uci -q get network.wan.ifname)
        proto=$(uci -q get network.wan.proto)
        if [ -n "$wanif" -a "$proto" == "dhcp" ]; then
            procd_open_instance
            procd_set_param command "$PROG" -C -i "$wanif"
            procd_set_param respawn
            procd_close_instance
        fi
    elif [ "$INITTED" = "YES" ]; then
        #CAP
        lanif="br-lan"
        procd_open_instance
        procd_set_param command "$PROG" -S -i "$lanif"
        procd_set_param respawn
        procd_close_instance
    fi
}
